
# Disable the newline at the start of the prompt
add_newline = false
# Overwrite a default_prompt_order and  use custom prompt_order
#prompt_order=["rust","line_break","package","line_break","character"]
# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 10
[character]      # The name of the module we are configuring is "character"
symbol = ""     # The "symbol" segment is being set to "➜"
