#git aliases
alias gs="git status"

#vim aliases
alias vim="/usr/local/Cellar/neovim/0.1.2/bin/nvim"
alias vi="/usr/local/Cellar/neovim/0.1.2/bin/nvim"
alias nvim="/usr/local/Cellar/neovim/0.1.2/bin/nvim"
alias neovim="/usr/local/Cellar/neovim/0.1.2/bin/nvim"

